let x = 'Good morning';
y = x.charAt(2);
console.log(y);
console.log('---------ex2----------');
let a = 'My father is a farmer';
b = a.charAt(5);
console.log(b);
console.log('---------ex3----------');
let c = 'How are you';
d = c.charAt(7);
console.log(d);
console.log('---------ex4----------');
let e = 'How old you are';
f = e.charAt(5);
console.log(f);
console.log('---------ex5----------');
let g = 'My laptop is dell';
h = g.charAt(8);
console.log(h);
console.log('---------ex6----------');
let i = 'I am good';
j = i.charAt(2);
console.log(j);
console.log('---------ex7----------');
let k = 'I want to study more';
l = k.charAt(9);
console.log(l);
console.log('---------ex8----------');
let m = 'facebook is a social media';
n = m.charAt(3);
console.log(n);
console.log('---------ex9----------');
let  o = 'good afternoon';
p = o.charAt(7);
console.log(p);
console.log('---------ex10----------');
let  q = 'we are all together';
r = q.charAt(6);
console.log(r);

