let x = 'Good morning';
y = x.concat(', Everyone');
console.log(y);
console.log('---------ex2----------');
let a = 'My father is a farmer';
b = a.concat(' and  i miss him');
console.log(b);
console.log('---------ex3----------');
let c = 'How are you';
d = c.concat('?');
console.log(d);
console.log('---------ex4----------');
let e = 'How old you are';
f = e.concat('?');
console.log(f);
console.log('---------ex5----------');
let g = 'My laptop is dell';
h = g.concat('!!!!!!');
console.log(h);
console.log('---------ex6----------');
let i = 'I am good';
j = i.concat('. What about you');
console.log(j);
console.log('---------ex7----------');
let k = 'I want to study more';
l = k.concat('. Because i need job');
console.log(l);
console.log('---------ex8----------');
let m = 'facebook is a social media';
n = m.concat('. SO most of them are having FB account');
console.log(n);
console.log('---------ex9----------');
let  o = 'good afternoon';
p = o.concat(', Everyone');
console.log(p);
console.log('---------ex10----------');
let  q = 'we are all together';
r = q.concat('!!!!!!');
console.log(r);