let x = 'Good morning';
y = x.includes('ning');
console.log(y);
console.log('---------ex2----------');
let a = 'My father is a farmer';
b = a.includes('father');
console.log(b);
console.log('---------ex3----------');
let c = 'How are you';
d = c.includes('you');
console.log(d);
console.log('---------ex4----------');
let e = 'How old you are';
f = e.includes('old');
console.log(f);
console.log('---------ex5----------');
let g = 'My laptop is dell';
h = g.includes('top');
console.log(h);
console.log('---------ex6----------');
let i = 'I am good';
// j = i.includes('good',3);
j = i.includes('good',7);
console.log(j);
console.log('---------ex7----------');
let k = 'I want to study more';
l = k.includes('study');
console.log(l);
console.log('---------ex8----------');
let m = 'facebook is a social media';
n = m.includes('book',2);
console.log(n);
console.log('---------ex9----------');
let  o = 'good afternoon';
p = o.includes('ood',0);
console.log(p);
console.log('---------ex10----------');
let  q = 'we are all together';
r = q.includes('together',5);
console.log(r);

