let str = 'Good Morning';
str1 = str.indexOf('od',0);
console.log('Index of od: ',str1);
console.log('------------------');
str2 = str.indexOf('o',3);
console.log('Index of o: ',str2);
console.log('---------ex2---------');
let data = 'This is the example';
a = data.indexOf('th',2);
console.log(a);
console.log('------------------');
a = data.indexOf('Th',2);
console.log(a);
console.log('------------------');
a = data.indexOf('is',2);
console.log(a);
console.log('-------ex3-----------');
let s = 'Java Script is scripting language';
b= s.indexOf('java',0); // case-sensitive
console.log(b);
console.log('------------------');
b= s.indexOf('Java',0); 
console.log(b);
console.log('-------ex4-----------');
let m = 'Laptop is mine';
c = m.indexOf('top',2);
console.log(c);
console.log('-------ex5-----------');
let y = 'Scripting language';
d = y.indexOf(" ",0);
console.log(d);

console.log('-------ex6-----------');
var r = 'Resume';
e = r.indexOf('s',0);
console.log(e);
console.log('-------ex7-----------');
var w = 'Programming language';
f = w.indexOf('mm',3);
console.log(f);
console.log('-------ex8-----------');
var k = 'car is a four-wheeler vehicle';
g = k.indexOf('-',2);
console.log(g);
console.log('-------ex9-----------');
var q = 'gmail.com';
i = q.indexOf('.com',5);
console.log(i);
console.log('-------ex10-----------');
var p = 'I love chicken';
l = p.indexOf('ick',4);
console.log(l);
