let x = 'Good morning';
y = x.replace('oo','u');
console.log(y);
console.log('---------ex2----------');
let a = 'My father is a farmer';
b = a.replace('My','mi');
console.log(b);
console.log('---------ex3----------');
let c = 'How are you';
d = c.replace('are','r');
console.log(d);
console.log('---------ex4----------');
let e = 'How old you are';
f = e.replace('you','u');
console.log(f);
console.log('---------ex5----------');
let g = 'My laptop is dell';
h = g.replace('My','mi');
console.log(h);
console.log('---------ex6----------');
let i = 'I am good';
j = i.replace('good','gud');
console.log(j);
console.log('---------ex7----------');
let k = 'I want to study more';
l = k.replace('more','much');
console.log(l);
console.log('---------ex8----------');
let m = 'facebook is a social media';
n = m.replace('face','Face');
console.log(n);
console.log('---------ex9----------');
let  o = 'good afternoon';
p = o.replace('good','Gud');
console.log(p);
console.log('---------ex10----------');
let  q = 'we are all together';
r = q.replace('are','r');
console.log(r);

