let x = 'Good morning';
y = x.search('ood');
console.log(y);
console.log('---------ex2----------');
let a = 'My father is a farmer';
b = a.search('a');
console.log(b);
console.log('---------ex3----------');
let c = 'How are you';
d = c.search('you');
console.log(d);
console.log('---------ex4----------');
let e = 'How old you are';
f = e.search('that');
console.log(f);
console.log('---------ex5----------');
let g = 'My laptop is dell';
h = g.search('is');
console.log(h);
console.log('---------ex6----------');
let i = 'I am good';
j = i.search('am');
console.log(j);
console.log('---------ex7----------');
let k = 'I want to study more';
l = k.search('to');
console.log(l);
console.log('---------ex8----------');
let m = 'facebook is a social media';
n = m.search('media');
console.log(n);
console.log('---------ex9----------');
let  o = 'good afternoon';
p = o.search('noon');
console.log(p);
console.log('---------ex10----------');
let  q = 'we are all together';
r = q.search('all');
console.log(r);

