let str = 'Good Morning';
str1 = str.split('o');
console.log(str1);
console.log('---------ex2---------');
let data = 'This is the example';
a = data.split('th');
console.log(a);
console.log('-------ex3-----------');
let s = 'Java Script is a scripting language';
b= s.split('java'); // case-sensitive
console.log(b);
console.log('-------ex4-----------');
let m = 'Laptop is mine';
c = m.split('top');
console.log(c);
console.log('-------ex5-----------');
let y = 'Scripting language';
d = y.split('ing');
console.log(d);
console.log('-------ex6-----------');
var r = 'Resume';
e = r.split('sume');
console.log(e);
console.log('-------ex7-----------');
var w = 'Programming language';
f = w.split('mming',3);
console.log(f);
console.log('-------ex8-----------');
var k = 'car is a four-wheeler vehicle';
g = k.split('-');
console.log(g);
console.log('-------ex9-----------');
var q = 'gmail.com';
i = q.split('.');
console.log(i);
console.log('-------ex10-----------');
var p = 'I love chicken';
l = p.split('o'); 
console.log(l);
