let x = 'Good morning';
// y = x.substr(0,2);
w = x.substr(0,5);
console.log(w);
console.log('---------ex2----------');
let a = 'My father is a farmer';
b = a.substr(1,3);
console.log(b);
console.log('---------ex3----------');
let c = 'How are you';
d = c.substr(0,7);
console.log(d);
console.log('---------ex4----------');
let e = 'How old you are';
f = e.substr(3,10);
console.log(f);
console.log('---------ex5----------');
let g = 'My laptop is dell';
h = g.substr(0,8);
console.log(h);
console.log('---------ex6----------');
let i = 'I am good';
j = i.substr(2);
console.log(j);
console.log('---------ex7----------');
let k = 'I want to study more';
l = k.substr(5,11);
console.log(l);
console.log('---------ex8----------');
let m = 'facebook is a social media';
n = m.substr(3,14);
console.log(n);
console.log('---------ex9----------');
let  o = 'good afternoon';
p = o.substr(0,9);
console.log(p);
console.log('---------ex10----------');
let  q = 'we are all together';
r = q.substr(0,10);
console.log(r);