let str = 'Good morning';
str = str.toUpperCase();
console.log(str);
console.log('---------ex2----------');
let a = 'My father is a farmer';
b = a.toUpperCase();
console.log(b);
console.log('---------ex3----------');
let c = 'How are you';
d = c.toUpperCase();
console.log(d);
console.log('---------ex4----------');
let e = 'How old you are';
f = e.toUpperCase();
console.log(f);
console.log('---------ex5----------');
let g = 'My laptop is dell';
h = g.toUpperCase();
console.log(h);
console.log('---------ex6----------');
let i = 'I am good';
j = i.toUpperCase();
console.log(j);
console.log('---------ex7----------');
let k = 'I want to study more';
l = k.toUpperCase();
console.log(l);
console.log('---------ex8----------');
let m = 'facebook is a social media';
n = m.toLocaleLowerCase();
console.log(n);
console.log('---------ex9----------');
let  o = 'good afternoon';
p = o.toUpperCase();
console.log(p);
console.log('---------ex10----------');
let  q = 'we are all together';
r = q.toUpperCase();
console.log(r);

console.log('==================')
console.log('toLowerCase');
let str1 = 'Good morning';
str2 = str1.toLowerCase();
console.log(str2);
console.log('---------ex2----------');
let y = 'My father is a farmer';
z = y.toLowerCase();
console.log(z);
console.log('---------ex3----------');
let c1 = 'How are you';
d1 = c1.toLowerCase();
console.log(d1);
console.log('---------ex4----------');
let e1 = 'How old you are';
f1 = e1.toLowerCase();
console.log(f1);
console.log('---------ex5----------');
let g1 = 'My laptop is dell';
h1 = g1.toLowerCase();
console.log(h1);
console.log('---------ex6----------');
let i1 = 'I am good';
j1 = i1.toLowerCase();
console.log(j1);
console.log('---------ex7----------');
let k1 = 'I want to study more';
l1 = k1.toLowerCase();
console.log(l1);
console.log('---------ex8----------');
let m1 = 'facebook is a social media';
n1 = m1.toLowerCase();
console.log(n1);
console.log('---------ex9----------');
let  o1 = 'good afternoon';
p1 = o1.toLowerCase();
console.log(p1);
console.log('---------ex10----------');
let  q1 = 'we are all together';
r1 = q1.toLowerCase();
console.log(r1);

