let str = '  Good morning ';
str = str.trim();
console.log(str);
console.log('---------ex2----------');
let a = '  My father is a farmer';
b = a.trim();
console.log(b);
console.log('---------ex3----------');
let c = '  How are you     ';
d = c.trim();
console.log(d);
console.log('---------ex4----------');
let e = '    How old you are  ';
f = e.trim();
console.log(f);
console.log('---------ex5----------');
let g = '     My laptop is dell     ';
h = g.trim();
console.log(h);
console.log('---------ex6----------');
let i = '    I am good      ';
j = i.trim();
console.log(j);
console.log('---------ex7----------');
let k = '   I want to study more   ';
l = k.trim();
console.log(l);
console.log('---------ex8----------');
let m = '   facebook is a social media';
n = m.trim();
console.log(n);
console.log('---------ex9----------');
let  o = '  good afternoon  ';
p = o.trim();
console.log(p);
console.log('---------ex10----------');
let  q = '  we are all together     ';
r = q.trim();
console.log(r);